/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _IndexRoute } from '../pages/';
import { Route as _ShakeAdRoute } from '../pages/shake-ad';

declare module '@granite-js/react-native' {
  interface RegisterScreen {
    '/': ReturnType<typeof _IndexRoute.useParams>;
    '/shake-ad': ReturnType<typeof _ShakeAdRoute.useParams>;
  }
}
