/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _IndexRoute } from '../pages/';
import { Route as _RecommendationRoute } from '../pages/recommendation';
import { Route as _WatchAdRoute } from '../pages/watch-ad';

declare module '@granite-js/react-native' {
  interface RegisterScreen {
    '/': ReturnType<typeof _IndexRoute.useParams>;
    '/recommendation': ReturnType<typeof _RecommendationRoute.useParams>;
    '/watch-ad': ReturnType<typeof _WatchAdRoute.useParams>;
  }
}
